### ISSUE TITLE
Missing ligatures?

### ISSUE THREAD

**Issue by fefe17** [SorkinType/Merriweather#141]
I installed the Merriweather variable fonts in my Linux system and opened a test web page in firefox that I use to test typefaces. I noticed, with Merriweather, that I don´t get common ligatures like fi or ft.

The page uses this CSS:

* { text-rendering: optimizeLegibility; font-variant-ligatures: common-ligatures; font-kerning: normal; font-feature-settings: "kern", "liga"; }

With other fonts I get working ligatures.

Am I doing something wrong or does Merriweather not have those ligatures?
Are these maybe only available in a commercial "pro" version or so?

Sorry if I missed something obvious!

**Comment by EbenSorkin** [comment]
The ligatures should be technically there however they are designed to look
as if they are not. E.g. They are designed to look as if you just typed f
and then i (or f and then t). The reason they are there is not to look
different but to accommodate ytexts in which those ligatures have been hard
coded. The reason for this is that at the intended size use that
merriweather was designed for legibility is the main concern. Also
Merriweather does not have a wide f! For this use size a consistent spacing
and rhythm is the main virtue to be had. The sense of flourish that a
ligature is meant to provide is in contrast somewhat besides the point. I
am making display versions now that are meant to be used large and there I
may change things for them. At large sizes and with tighter spacing
ligatures could be helpful or at least offer another viable visual solution.

It is also possible you installed old files. Where did they come from?

-e.
