### ISSUE TITLE
The letter "u" of the font "Merriweather" in mode bold is larger than other letters - Bug only on Windows

### ISSUE THREAD

**Issue by smtxdev** [SorkinType/Merriweather#394]
Hello ladies and gentleman, 

I would like to share an issue with you. In particular with the font "Merriweather" in mode "bold". The letter "u" of this font is slightly larger than the other letters. This issue only occurs on Windows. On Mac this issue does not exist.

It would be very kind if you could fix this issue.

Following an image of the issue. As you can see the letter "u" is a bit larger than the other letters.

![image](https://user-images.githubusercontent.com/45975452/68389145-8fd8e300-0162-11ea-9702-9c843206c658.png)

![image](https://user-images.githubusercontent.com/45975452/68389608-acc1e600-0163-11ea-9703-5c5b68ac8ca0.png)

Thank you in advance.

**Comment by EbenSorkin** [comment]
What Windows version/s did you see this in?

Was rendered in a browser or somewhere else?

What size this? What units? pts or px or em?

-e.
