### ISSUE TITLE
adjustments to B, A, M per note

### ISSUE THREAD

**Issue by joyceketterer** [SorkinType/Merriweather#466]
Merriweather - UC PDF feedback - Small optical - Light & Black Widths
Wide 

I would like to darken this slightly by letting the side bearings of a few letters be pulled in a but more : Right side of B, Both sides of A, both sides of M

Small Optical Black Widths-
Again, the even color overall is really nice! 
 per email of 9/11

**Comment by EbenSorkin** [comment]
fixed
