### ISSUE TITLE
Merriweather italic - Diacritics - new file v12

### ISSUE THREAD

**Issue by joyceketterer** [SorkinType/Merriweather#471]
notes per 10/2 email

This file has a lot of new material in the form of lowercase, uppercase and symbols. Its numbers and punctuation are not as up to date yet.

I have worked to carefully manually catch things that didn't make it in the with the merge but you may still find things I missed. I hope not.

Almost all the glyphs interpolate now which is something I need in general but also something I need to show Dave what we have for Italic so far in intermediate optical sizes.

• However the following Glyphs don't interpolate. Please correct this: commaturnedabovecomb.case, horncomb.case, circumflexcomb_acutecomb, circumflexcomb_gravecomb, circumflexcomb_hookabovecomb, brevecomb_acutecomb.case, brevecomb_gravecomb.case, brevecomb_hookabovecomb.case, brevecomb_tildecomb.case, circumflexcomb_acutecomb.case, circumflexcomb_gravecomb.case, circumflexcomb_hookabovecomb.case, circumflexcomb_tildecomb.case,

• I re-treated the horn diacritic and made a system that is rational and works for uhorn. I have not checked how it work for U or o or O yet please give that a try. Assuming the this is a good general approach the glyph horncomb.case can follow or copy it.

• The excellent display diacritics have been copied to display widths and adjusted +6 or -6. These have not been adjusted for angle. I think I have done the whole of the base comb set but not all of the comb.case. 

I did get to these however dieresiscomb.case, dotaccentcomb.case, gravecomb.case, ringcomb.case, 

In any event please have a look at these adjusted versions and if you are happy with this method feel free to use it on the comb.cap diacritics. 

• In the case of the narrow and wide small optical .comb diacritics I have also treated these with +6 or -6 width scaling but not adjusted placement or angle. Please also adjust these.

• I really liked what you did with the comma mark diacritical mark 'commaturnedabovecomb' because it matches our italic comma. I updated it to interpolate and to have widths and have commaturnedabovecomb mirroring it. 

Now I would like you make these match that approach : commaturnedabovecomb.case, commaaccentcomb.case,

• I like your approach to strokeshortcomb, strokelongcomb, slashshortcomb, slashlongcomb,. 

For display I have adjusted strokeshortcomb to use the stroke thickness used in the rest of the design - in symbols for example. I have not adjusted it's width however so please do that. Please update strokelongcomb to use the same stroke thickness and adapt this to look similar in display slashshortcomb, slashlongcomb

• Please check to see if the anchor heights being used are consistent. Mostly they are but this check is needed to be done.

Please let me know if you have any questions and when you have had a chance to evaluate this if you could give me a sense of when you think we should see a push that would be great. It seems to me like it might be possible to complete this during the next seven days because fundamentally the core display is in very good shape. But let me know what you think. 

Notes: 

- The glyphs "dieresis, dotaccent, grave, acute, hungarumlaut, circumflex, caron, breve, ring, tilde, macron, cedilla, ogonek," have all been made to use side bearings linked to hyphen and they are made with linked copies of the combining diacritics. You don't need to worry about these. You can consider them done.

- The Upper case and lower case latin should be in good enough shape that you can evaluate the diacritics. The Small Caps are not especially because their anchor placement isn't resolved. I have only checked O, A and E and even these may not be using final anchor heights especially in display. So it is Ok to ignore Small caps.

**Comment by EbenSorkin** [comment]
fixed
