### ISSUE TITLE
Cyrillic sans

### ISSUE THREAD

**Issue by chepulis** [SorkinType/Merriweather#475]
Hi. I saw:
> you can request improvements

 and i thought that i should request an improvement.

This is a fantastic family you've created and it answers almost all of my needs. Except that the Merriweather Sans, sadly, lacks cyrillic support. This doesn't seem to be on the roadmap, so here's a vote from a random user who thinks it should.

Good luck!

**Comment by EbenSorkin** [comment]
I would *love* to add this. I am not sure if it will happen this year. I
will see if I can get funding for it.

-e.
