### ISSUE TITLE
Per email dated 11.27.19

### ISSUE THREAD

**Issue by joyceketterer** [SorkinType/Merriweather#476]
MW Light Display Narrow

• N+i looks wide to me- compare to the space between nn. We don't need to keep this wide for diacritics because we have a script for that.
• l spacing - I think the base spacing is too small in general comparing  but more critically the new spacing of Riddle is much too tight where the l comes in. Compare Riddle to Mills! Mills is much closer to what we want.
• r - right side bearing adjust +10
• K+a closer please
• CC too close now. 
• GG too close as well MW Light Display Wide
• F+u even a bit tighter please
• V+o a little tighter please
• N+i looks wide to me - tighter please
• r - right side bearing adjust +10

**Comment by EbenSorkin** [comment]
fixed
