### ISSUE TITLE
Download latest otf font files

### ISSUE THREAD

**Issue by medmedin2014** [SorkinType/Merriweather#478]
In releases section there is only an old version 1.582, how can I get the new one 2.005 because I tried for two days to build them using python3 on my KUbuntu but never build otf files. Can anyone please post a download link to latest otf files please ?

**Comment by EbenSorkin** [comment]
We are going to release 2.006 quite soon which is a much bigger family. I
think it should be 2 weeks out now.

It is quite a deep improvement again so if you can I would recommend that
you wait for that.

-e.

**Comment by medmedin2014** [comment]
@EbenSorkin Thanks really for the hard work, I love this font so much elegant, professional and easy to read on my slides and reports ;)
