### ISSUE TITLE
Q: Arbitrary number systems in source files - Weight

### ISSUE THREAD

**Issue by EbenSorkin** [SorkinType/Merriweather#482]
In the Glyphs source file in the "axes coordinates" for weight I am using the measured width of a stem. 

This may be fine. 

Or it may be that there are good reasons to snap the values to use the century CSS values in the source file instead only using century values in the "axes location custom parameter".

Which is it? Why?

**Comment by EbenSorkin** [comment]
looking here:
[https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wght](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wght)
Where it says: "In a variable font that implements 'wght' variations, the value in the usWeightClass field of the OS/2 table must match the default 'wght' value specified in the 'fvar' table." It seems clear that the masters weight values in the VF in named instances should be centuries. But that was known. 

It isn't clear to me yet if that means that the source file should as well yet too. 

Could using the Glyphs custom Parameter "weightClass" in instances solve any issues? Or maybe editing the VF after the fact an inserting or editing a stat table is required?

I plan to test the custom Parameter "weightClass" using the roman unless Dave or Marc have a better idea or other advice.

**Comment by davelab6** [comment]
I believe that is correct, you use the Glyphs custom Parameter "weightClass" (or something) to map your master values to the VF designSpace values.

**Comment by EbenSorkin** [comment]
Seems fixed
