### ISSUE TITLE
Q: Arbitrary number systems in source files - Optical size

### ISSUE THREAD

**Issue by EbenSorkin** [SorkinType/Merriweather#483]
In the Glyphs source file For Optical Size Axes Coordinate I am using a theoretically ideal optical size use for the design. 

e.g. If the master is designed to be used at 144pt then the coordinate is 144. 

However is this ideal? Are there prefered century or other values for this now?

-e.

**Comment by EbenSorkin** [comment]
The Values use based on what I see here seem fine.

[https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz)

So I'll close this one.

**Comment by EbenSorkin** [comment]
I am re-opening this because I don't think it is a good idea for Fontmake to have the smallest possible optical size be 12. 6 or 7pt would make more sense. Admittedly it won't be use a lot but is the tool for typography or JUST webfonts?

**Comment by davelab6** [comment]
The suggestion of 12 in the [dvaraxistag_opsz](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz) page is just a suggestion.

**Comment by EbenSorkin** [comment]
I was able to reset the min value to 7.
