### ISSUE TITLE
Q: Arbitrary number systems in source files - Width

### ISSUE THREAD

**Issue by EbenSorkin** [SorkinType/Merriweather#484]
Right now the values being used for width in the Glyphs source are really arbitrary. Width is 125 for wide 100 for regular and 80 for narrow. 

Unlike the weight this arbitrary value is in the VF axis data. 

Are there prefered standard values matching wideness names now? Are they century numbers?

**Comment by EbenSorkin** [comment]
In the spec here:
[https://github.com/googlefonts/gf-docs/tree/master/Spec#variable-fonts](https://github.com/googlefonts/gf-docs/tree/master/Spec#variable-fonts)
It says regular should be 100 ( it is ) and links to the MS spec
[https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth)
Looking at the MS table in the linked page seems to suggest that the name for the _Narrow_ should instead be _Semicondensed_ and the VF axis value should be 87. The _Wide_ should be _Semi-expanded_ and the VF axis value should be 112. I am not so keen on the names which seem too long but the axis values are fine.

**Comment by davelab6** [comment]
I just looked at this for https://github.com/TypeNetwork/Roboto-Flex with @dberlow and decided to use the opsz-max range of widths; that is, to calculate as percentages, when opsz is max, the distance from the width-min and width-max to the width-default. 

@dberlow is that a correct summary of your process to determine the range of the `wdth` axis in Roboto Flex? Is there any more detail you can add, such as the exactly process to measure the distance?

**Comment by EbenSorkin** [comment]
This seems to be fixed now.
