### ISSUE TITLE
Collaboration suggestion

### ISSUE THREAD

**Issue by davelab6** [SorkinType/Merriweather#5]
Having over a dozen contributors join this project, with varying levels of familiarity with git, is an interesting challenge. 

My suggestion is that each contributor be given push access to a single development branch, and that they each work **only** in "their own" separate folders, and commit and push/pull constantly with `git pull --rebase`. 

By each working in a separate folder, they should not introduce any merge conflicts, and by doing rebase pulls, they should just get the updates from the other folks. 

Then the merging can be done by hand, using the MergeGlyphs tool from www.glyphsapp.com

**Comment by EbenSorkin** [comment]
Great. I'll go ahead and add folders in their names. Will Github desktop be the appropriate tool given the  `git pull --rebase` command or should that be done command line only?

**Comment by EbenSorkin** [comment]
I have added the folders now.

**Comment by EbenSorkin** [comment]
Dave what do you think of this for the contractors? 

https://git-fork.com/

**Comment by davelab6** [comment]
Its not libre but its $0 

The homepage describes that it has "Interactive Rebase" so its probably able to sync changes fine without creating conflicts or merges.

**Comment by EbenSorkin** [comment]
Thanks for the feedback. I’ll give it test and if good I’ll distribute the info and get people used to using it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by davelab6** [comment]
I am curious where this ended up - are people using SourceTree, Git Fork, or som other GUI?
