### ISSUE TITLE
K, L interpolation issue in semiexpanded italic style

### ISSUE THREAD

**Issue by Cogli** [SorkinType/Merriweather#511]
![Asset 1@2x-100](https://user-images.githubusercontent.com/55837580/84568590-b5753d00-ad80-11ea-85e6-a3d4076a107d.jpg)

This is Text Semiexpanded Italic but the same show up throughout all opsz. The image was generated with the static otfs, but still the issue seems to occur in vf files.

**Comment by EbenSorkin** [comment]
I’ll look to fix this over the weekend

**Comment by EbenSorkin** [comment]
I just checked the version that pushed last night and it appears to be fixed.

**Comment by Cogli** [comment]
ok, I cannot check glyphsapp files, but in current fonts folder of this repository, both otfs and ttfs still show up wrong outlines.

I took a look at .ufos in source folder: in light-wide-italic and black-wide-italic, path direction and starting point for K glyph are different. Not sure if this is a problem, afterall, but I hope this can help!

Thank you!

**Comment by EbenSorkin** [comment]
I looked again and I see the problem. I have fixed the source but I have not pushed them or new OTFs TTFs  & VFs. That should happen this evening. Thanks for your persistence.

**Comment by Cogli** [comment]
Thank you and everyone who works on the project.

**Comment by EbenSorkin** [comment]
Fixed in the files being uploaded now.
