### ISSUE TITLE
Test:  Upright Latin Smallcaps (esthetic fix to A)

### ISSUE THREAD

**Issue by joyceketterer** [SorkinType/Merriweather#53]
Ask you to reform the small optical size version. 
I think 1 is the thing that makes sense for reasons of continuity with the existing design. 2) seems too painful 3) makes sense if you can make a case why the JFP le-monde version is somehow degenerate. The thing is I chose this style because it seems more robust for low rez screens. And that time has past... So in theory I could be open to changing this. But I would need a strong reason I think. Do you have one?

**Comment by EbenSorkin** [comment]
This was just a test.
