### ISSUE TITLE
Tags & Releases

### ISSUE THREAD

**Issue by jessestricker** [SorkinType/Merriweather#7]
Hi,

I was trying to find the latest stable version of the fonts to download, but could not find a tag/release for v2.005.

By inspecting the commit log, I guess that commit ae0bf55e53517ac98cc74c375a383ad4c36f937a relates to this version.

I think it would greatly improve the usability of this repository, if you could assign each release commit with a respective tag.

**Comment by EbenSorkin** [comment]
You can take fonts from this location 
https://github.com/SorkinType/Merriweather/tree/master/fonts

However you are right. There should be a new formal release. I should be able to get that done this week.

**Comment by jessestricker** [comment]
Thank you!
